version: '3.7'

services:
  server:
    container_name: server_container
    hostname: server_host
    build: backend/.
    ports:
      - 8080:8080
    #env_file:
    #  - backend/.env
    environment:
      DB_HOST: postgres_alias
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: area
    networks:
      webnet:
        aliases:
          - server_alias
    depends_on:
      - postgres
  web:
    container_name: web_container
    hostname: web_host
    build: website/.
    ports:
      - 8081:8081
    networks: 
      - webnet
    depends_on:
      - server
  postgres:
    container_name: postgres_container
    hostname: postgres_host
    image: postgres:12
    networks:
      webnet:
        aliases: 
          - postgres_alias
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: area
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
    driver: bridge
volumes:
  pgdata: