version: '3'

services:
  web:
    build: .
    ports:
    - "8080:8081"
    volumes:
    - .:/code
    links:
    - server
    - mobile
  mobile:
    build: .
    volumes:
    - .:/code
  server:
    ports:
    - "8080:8080"
  mongodb:
    image: mongo
    ports:
    - "27017:27017"
